version: '3'
services:
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webnet
  gateway:
    image: FINAL-PROJECT-PICKLE-RICK/backend/gateway
    ports:
        "4000:4000"
    deploy:
        replicas: 1
    networks:
        - webnet
    environment: 
        - FRONT_END_HOST=http://frontend:3000
        - WEBSOCKET_HOST=http://websocket:4000/websocket
        - AUTH_HOST=http://authenticate:3001
        - INV_HOST=http://inventory:3005
        - RECEIPTS_HOST=http://receipts:3006
        - UPLOAD_HOST=http://upload:3002
  frontend:
    image : FINAL-PROJECT-PICKLE-RICK/final
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet 
  websocket:
    image : FINAL-PROJECT-PICKLE-RICK/websocket
    depends_on:
      - redis
    ports:
      - "4000:4000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
  authenticate:
    image : FINAL-PROJECT-PICKLE-RICK/authenticate
    ports:
      - "3001:3001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet 
  inventory:
    image : FINAL-PROJECT-PICKLE-RICK/inventory
    ports:
      - "3005:3005"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  receipts:
    image : FINAL-PROJECT-PICKLE-RICK/receipts
    ports:
      - "3006:3006"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  upload:
    image : FINAL-PROJECT-PICKLE-RICK/upload
    ports:
      - "3002:3002"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet        
  kafka:
    image : wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - webnet
networks:
  webnet: